#!/usr/bin/env tclsh

set data [read [open [lindex $argv 0] "r"]]
set outfp [open "lab2.2.1.output.txt" w]

#set cell_keywords {ELVT ULVT ULVTLL LVT LVTLL SVT CNOD}
#set cell_keywords {[0-9]x[0-9]}
set cell_keywords {VIOLATED}
set total_cells 0

foreach line [split $data "\n"] {

    set line [string trim $line]
    if {$line eq ""} { continue }

    regsub -all {\s+} $line " " clean
    set tokens [split $clean " "]
    # Reset biến để tránh lỗi
    set cell ""
   set col2 ""

    set col1 [lindex $tokens 1]
  set col2 [lindex $tokens end]

   # if {[string match *net* $col2]} {
#          continue}

    foreach key $cell_keywords {
        if {[string match *$key* $col1]} {
        set cell $col1
            break
        }
    }

    # Kiểm tra cell không rỗng
    if {$cell ne ""} {
   puts "$cell $col2"
        puts "$cell"
        incr total_cells
    }
}
puts "Total cells found: $total_cells"
close $outfp
